# modules/bio — reusable protein-design / ML-biology toolkit.
#
# Provides `bio-*` command-line wrappers around a set of bare models
# (AlphaFold 3, RFdiffusion, RoseTTAFold-All-Atom, ProteinMPNN, ESM-2,
# EVOLVEpro) plus PyMOL for visualization.
#
# Design goals:
#   * Reproducible & version-controlled: pinned git refs + pinned Python
#     requirements live in this repo; the module installs the wrappers,
#     setup scripts and a machine-specific /etc/bio/config.sh into the store.
#   * Generalizable across machines: everything hardware-specific is an
#     `options.bio.*` knob. A cloud-GPU machine reuses this module verbatim
#     and just raises `bio.gpu.vramGB` / `bio.esm.defaultModel`, etc.
#   * Runs pip/CUDA wheels natively on NixOS via `programs.nix-ld`; the heavy
#     Python deps install into per-tool `uv` venvs under `bio.dataDir`
#     (mutable state, kept out of the Nix store) by `bio-setup`.
{ config, lib, pkgs, ... }:

let
  cfg = config.bio;

  # Interpreters we make available for `uv venv --python`. ProteinMPNN/ESM/
  # EVOLVEpro use 3.11 and AlphaFold 3 uses 3.12 — both native Nix interpreters,
  # so their pip/CUDA wheels import via the normal linker + LD_LIBRARY_PATH (below)
  # and don't depend on nix-ld. RFdiffusion (torch 1.12 → cp310 only) and RFAA
  # (pinned 3.10) have no 3.10 in this nixpkgs, so bio-setup lets `uv` fetch a
  # managed CPython 3.10 — that one DOES run via nix-ld (kept enabled below).
  pythons = with pkgs; [ python311 python312 ];

  # Shared libs the manylinux CUDA wheels dlopen at runtime: libstdc++/libgcc_s/
  # libgomp and zlib. Combined with the NVIDIA driver dir this lets torch/jax load
  # under a Nix-native Python without an FHS/conda shim.
  wheelLibPath = "${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.zlib}/lib";

  # Tools every bio-* wrapper/setup script may need on PATH.
  commonRuntime = with pkgs; [
    uv git git-lfs wget curl aria2 cacert
    gnutar gzip bzip2 xz zstd unzip
    coreutils findutils gnugrep gnused gawk which procps hostname
  ] ++ pythons;

  # Wrap a script file from ./scripts as a `bio-*` command with a hermetic PATH.
  # writeShellScriptBin (not writeShellApplication) so the dynamic, config-sourcing
  # scripts aren't blocked by style-level shellcheck lints; a bash -n syntax check
  # still runs at build time.
  mkBioCmd = { name, runtimeInputs ? [ ] }:
    pkgs.writeShellScriptBin name ''
      export PATH=${lib.makeBinPath (commonRuntime ++ runtimeInputs)}''${PATH:+:$PATH}
      ${lib.optionalString (builtins.elem name [ "bio-library" "bio-library-backup" ]) ''
        export BIO_LIBRARY_CLIENT=''${BIO_LIBRARY_CLIENT:-${./py/library_client.py}}
        export BIO_LIBRARY_REGISTRY=''${BIO_LIBRARY_REGISTRY:-${../../machines/head/library/registry.py}}
      ''}
      set -o pipefail
      ${builtins.readFile (./scripts + "/${name}.sh")}
    '';

  enabledTools = lib.filterAttrs (_: t: t.enable) cfg.tools;

  bioCommands =
    # Always-on helpers.
    [
      (mkBioCmd { name = "bio-doctor"; })
      (mkBioCmd { name = "bio-setup"; })
      # laptop-side: run a cluster model, fetch the result, view/render locally
      (mkBioCmd { name = "bio-fold"; runtimeInputs = [ pkgs.openssh pkgs.rsync ]; })
      (mkBioCmd { name = "bio-library"; runtimeInputs = [ pkgs.openssh ]; })
      (mkBioCmd { name = "bio-library-backup"; runtimeInputs = [ pkgs.openssh ]; })
    ]
    # Per-tool run wrappers, gated on their enable flag.
    ++ lib.optional cfg.tools.esm.enable (mkBioCmd { name = "bio-esm"; })
    ++ lib.optional cfg.tools.proteinmpnn.enable (mkBioCmd { name = "bio-mpnn"; })
    ++ lib.optional cfg.tools.evolvepro.enable (mkBioCmd { name = "bio-evolvepro"; })
    ++ lib.optional cfg.tools.rfdiffusion.enable (mkBioCmd { name = "bio-rfdiffusion"; })
    ++ lib.optional cfg.tools.rfaa.enable (mkBioCmd { name = "bio-rfaa"; })
    ++ lib.optional cfg.tools.alphafold3.enable (mkBioCmd { name = "bio-af3"; })
    ++ lib.optional cfg.tools.pymol.enable (mkBioCmd { name = "bio-viz"; runtimeInputs = [ pkgs.pymol ]; });

  # /etc/bio/config.sh — the single source of machine-specific truth that
  # every bio-* script sources at runtime.
  configSh = pkgs.writeText "bio-config.sh" ''
    # Generated by modules/bio — do not edit by hand; change options.bio.* instead.
    export BIO_DATA_DIR=${lib.escapeShellArg cfg.dataDir}
    export BIO_USER=${lib.escapeShellArg cfg.user}
    export BIO_GROUP=${lib.escapeShellArg cfg.group}
    export BIO_GPU_VRAM_GB=${toString cfg.gpu.vramGB}
    export BIO_ESM_DEFAULT_MODEL=${lib.escapeShellArg cfg.esm.defaultModel}
    export BIO_TORCH_CUDA=${lib.escapeShellArg cfg.torchCudaWheel}

    # Cluster head used by the laptop-side `bio-fold` to run models remotely.
    export BIO_CLUSTER_HEAD=${lib.escapeShellArg cfg.cluster.head}
    export BIO_CLUSTER_USER=${lib.escapeShellArg cfg.cluster.user}
    export BIO_CLUSTER_SSHKEY=${lib.escapeShellArg cfg.cluster.sshKey}

    # NVIDIA userspace driver (libcuda.so.1) lives here on NixOS; CUDA wheels
    # dlopen it at runtime, so every wrapper prepends this to LD_LIBRARY_PATH.
    export BIO_DRIVER_LIB=/run/opengl-driver/lib
    # libstdc++/libgcc_s/libgomp + zlib the wheels need, from the Nix store.
    export BIO_WHEEL_LIB=${wheelLibPath}

    # CA bundle for uv/pip/requests inside venvs.
    export SSL_CERT_FILE=''${SSL_CERT_FILE:-/etc/ssl/certs/ca-bundle.crt}
    export REQUESTS_CA_BUNDLE=''${REQUESTS_CA_BUNDLE:-/etc/ssl/certs/ca-bundle.crt}

    # Where huggingface / torch caches go (kept under the data dir, not $HOME).
    export HF_HOME=''${HF_HOME:-$BIO_DATA_DIR/cache/huggingface}
    export TORCH_HOME=''${TORCH_HOME:-$BIO_DATA_DIR/cache/torch}

    # Per-tool enable flags (so bio-setup all knows what to build here).
    export BIO_ENABLE_ESM=${lib.boolToString cfg.tools.esm.enable}
    export BIO_ENABLE_PROTEINMPNN=${lib.boolToString cfg.tools.proteinmpnn.enable}
    export BIO_ENABLE_EVOLVEPRO=${lib.boolToString cfg.tools.evolvepro.enable}
    export BIO_ENABLE_RFDIFFUSION=${lib.boolToString cfg.tools.rfdiffusion.enable}
    export BIO_ENABLE_RFAA=${lib.boolToString cfg.tools.rfaa.enable}
    export BIO_ENABLE_AF3=${lib.boolToString cfg.tools.alphafold3.enable}
    export BIO_ENABLE_PYMOL=${lib.boolToString cfg.tools.pymol.enable}
  '';

in
{
  options.bio = {
    enable = lib.mkEnableOption "protein-design / ML-biology toolkit (bio-* CLIs)";

    dataDir = lib.mkOption {
      type = lib.types.str;
      default = "/opt/bio";
      description = ''
        Mutable directory holding per-tool venvs, cloned source repos, model
        weights and run outputs. Created (owned by `bio.user`) via tmpfiles.
        Deliberately outside the Nix store; populated by `bio-setup`.
      '';
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "aydin";
      description = "User that owns dataDir and runs bio-setup.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "users";
      description = "Group that owns dataDir.";
    };

    cudaCache = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Add the cuda-maintainers cachix substituter so any pure-Nix CUDA
        packages (torchWithCuda, jaxlib-cuda) come prebuilt instead of
        compiling for hours. Not required for the default pip-wheel install
        path, but useful and harmless.
      '';
    };

    torchCudaWheel = lib.mkOption {
      type = lib.types.str;
      default = "cu124";
      description = ''
        PyTorch CUDA wheel tag used for the download.pytorch.org extra index
        (e.g. "cu121", "cu124", "cu128", or "cpu"). The RTX 3070 (Ampere) +
        driver 595 handles any recent CUDA runtime.
      '';
    };

    gpu.vramGB = lib.mkOption {
      type = lib.types.int;
      default = 8;
      description = ''
        Approximate GPU VRAM in GB. Wrappers use this to pick safe defaults and
        to warn before launching a model that will not fit. A cloud-GPU machine
        sets this to e.g. 80.
      '';
    };

    esm.defaultModel = lib.mkOption {
      type = lib.types.str;
      default = "esm2_t33_650M_UR50D";
      example = "esm2_t48_15B_UR50D";
      description = ''
        Default ESM-2 checkpoint for `bio-esm` when --model is not given.
        650M fits comfortably in 8GB; bump to 3B/15B on a big-VRAM machine.
      '';
    };

    cluster = {
      head = lib.mkOption {
        type = lib.types.str;
        default = "31.56.109.100";
        description = "DataCrunch head node (IP or tailnet name) that `bio-fold` runs `bio-submit` on.";
      };
      user = lib.mkOption {
        type = lib.types.str;
        default = "root";
        description = "SSH user on the cluster head.";
      };
      sshKey = lib.mkOption {
        type = lib.types.str;
        default = "/home/${cfg.user}/.ssh/datacrunch_ed25519";
        description = "SSH private key `bio-fold` uses to reach the head + fetch results.";
      };
    };

    library.backup.enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Pull and restore-check an hourly construct-library snapshot while this user's workstation is running.";
    };

    tools = lib.mapAttrs
      (name: default: {
        enable = lib.mkOption {
          type = lib.types.bool;
          inherit default;
          description = "Install the ${name} bio-* wrapper and let bio-setup build its env.";
        };
      })
      {
        pymol = true;
        esm = true;
        proteinmpnn = true;
        evolvepro = true;
        rfdiffusion = true;
        rfaa = true;
        alphafold3 = true;
      };
  };

  config = lib.mkIf cfg.enable {
    # Keep scheduled pulls running while the workstation is on, including
    # after logout; Persistent timers catch up after the machine was offline.
    users.users.${cfg.user}.linger = lib.mkIf cfg.library.backup.enable true;
    # Run foreign (PyPI/CUDA) ELF binaries natively on NixOS.
    programs.nix-ld.enable = true;
    programs.nix-ld.libraries = with pkgs; [
      stdenv.cc.cc.lib # libstdc++, libgcc_s, libgomp
      zlib
      zstd
      bzip2
      xz
      openssl
      curl
      libffi
      ncurses
      readline
      expat
      libxml2
      libxslt
      glib
      util-linux # libuuid
      gmp
      mpfr
      libGL
      libGLU
      libx11
      libxext
      libxrender
      libsm
      libice
      freetype
      fontconfig.lib
      dbus.lib
      nss
      nspr
    ];

    nix.settings = lib.mkIf cfg.cudaCache {
      substituters = [ "https://cuda-maintainers.cachix.org" ];
      trusted-public-keys = [
        "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
      ];
    };

    # Materialize the mutable data dir with the right owner up front.
    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir}            0755 ${cfg.user} ${cfg.group} - -"
      "d ${cfg.dataDir}/envs       0755 ${cfg.user} ${cfg.group} - -"
      "d ${cfg.dataDir}/src        0755 ${cfg.user} ${cfg.group} - -"
      "d ${cfg.dataDir}/weights    0755 ${cfg.user} ${cfg.group} - -"
      "d ${cfg.dataDir}/runs       0755 ${cfg.user} ${cfg.group} - -"
      "d ${cfg.dataDir}/cache      0755 ${cfg.user} ${cfg.group} - -"
      "d ${cfg.dataDir}/logs       0755 ${cfg.user} ${cfg.group} - -"
    ];

    # Machine config + pinned requirements + helper python CLIs, all readable
    # at /etc/bio by the wrapper/setup scripts.
    environment.etc = {
      "bio/config.sh".source = configSh;

      "bio/requirements/esm2.txt".source = ./requirements/esm2.txt;
      "bio/requirements/proteinmpnn.txt".source = ./requirements/proteinmpnn.txt;
      "bio/requirements/evolvepro-core.txt".source = ./requirements/evolvepro-core.txt;
      "bio/requirements/evolvepro-plm.txt".source = ./requirements/evolvepro-plm.txt;
      "bio/requirements/rfdiffusion.txt".source = ./requirements/rfdiffusion.txt;
      "bio/requirements/rfaa.txt".source = ./requirements/rfaa.txt;
      "bio/requirements/alphafold3.txt".source = ./requirements/alphafold3.txt;

      "bio/py/esm_cli.py".source = ./py/esm_cli.py;
      "bio/py/evolvepro_cli.py".source = ./py/evolvepro_cli.py;
      "bio/py/viz.py".source = ./py/viz.py;
      "bio/py/clear_execstack.py".source = ./py/clear_execstack.py;
      "bio/py/rfaa_singleseq_patch.py".source = ./py/rfaa_singleseq_patch.py;
      "bio/py/library_client.py".source = ./py/library_client.py;
      "bio/library/registry.py".source = ../../machines/head/library/registry.py;
    };

    systemd.user.services.bio-library-backup = lib.mkIf cfg.library.backup.enable {
      description = "Fetch and restore-check the head construct library";
      unitConfig.ConditionUser = cfg.user;
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${mkBioCmd { name = "bio-library-backup"; runtimeInputs = [ pkgs.openssh ]; }}/bin/bio-library-backup";
        UMask = "0077";
        TimeoutStartSec = "30min";
      };
    };
    systemd.user.timers.bio-library-backup = lib.mkIf cfg.library.backup.enable {
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = "hourly";
        Persistent = true;
        RandomizedDelaySec = "5min";
      };
    };

    environment.systemPackages =
      bioCommands
      ++ lib.optional cfg.tools.pymol.enable pkgs.pymol
      # Build/runtime tooling that setup scripts and tool extensions may need.
      ++ (with pkgs; [
        uv
        git
        git-lfs
        wget
        aria2
        gcc # some pip packages build C/C++ extensions
        gnumake
        cmake
        ninja # AlphaFold 3 C++ data-pipeline build
        pkg-config
        hmmer # AF3 / RFAA MSA search (kalign/jackhmmer)
        kalign
      ]);
  };
}
