"""Canonical preparation admission and optional real-engine qualification.

Set BIO_MD_TEST_RUNTIME to a qualified local CPU prefix for the actual native
preparation tests. They perform preparation only, never mdrun or network calls.
"""
import copy
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

from md.preparation import DECISIONS, inspect_pdb, prepare, read_pdb, validate_templates


# Extended GAG geometry generated by the pinned pmx builder. A software fixture,
# not an experimental structure or a molecular-affinity benchmark.
GEOMETRY = [
    (1, 'GLY', 'N', (-4.409, -9.433, -1.254)), (1, 'GLY', 'CA', (-3.718, -8.173, -1.018)),
    (1, 'GLY', 'C', (-2.323, -8.471, -.459)), (1, 'GLY', 'O', (-2.194, -9.313, .432)),
    (2, 'ALA', 'N', (-1.264, -7.824, -.936)), (2, 'ALA', 'CA', (.058, -8.106, -.406)),
    (2, 'ALA', 'CB', (.742, -9.095, -1.358)), (2, 'ALA', 'C', (.879, -6.818, -.227)),
    (2, 'ALA', 'O', (.902, -5.960, -1.112)), (3, 'GLY', 'N', (1.573, -6.621, .891)),
    (3, 'GLY', 'CA', (2.350, -5.402, 1.060)), (3, 'GLY', 'C', (3.690, -5.756, 1.713)),
    (3, 'GLY', 'O', (3.712, -6.527, 2.674)),
]


def pdb(chains=('A',)):
    lines = []
    serial = 0
    for index, chain in enumerate(chains):
        for resid, residue, name, xyz in GEOMETRY:
            serial += 1
            x, y, z = xyz
            y += 15 * index
            lines.append(f'ATOM  {serial:5d} {name:>4} {residue:>3} {chain}{resid:4d}    '
                         f'{x:8.3f}{y:8.3f}{z:8.3f}{1:6.2f}{0:6.2f}          {name[0]:>2}')
        lines.append('TER')
    return ('\n'.join(lines) + '\nEND\n').encode()


def decisions():
    return {**DECISIONS, 'histidines': {}}


class PreparationAdmissionTests(unittest.TestCase):
    def inspect(self, value=None, chemistry=None, chains=None):
        return inspect_pdb(value if value is not None else pdb(), chemistry or decisions(), chains)

    def test_all_chains_are_retained_and_fixed_partner_selection_is_audited(self):
        value = pdb(('A', 'B'))
        both = self.inspect(value)
        self.assertEqual(both['selected_chains'], ['A', 'B'])
        self.assertEqual(len(both['residues']), 6)
        unbound = self.inspect(value, chains=['B'])
        self.assertEqual(unbound['selected_chains'], ['B'])
        self.assertEqual(unbound['excluded_chains'], ['A'])
        self.assertEqual(unbound['excluded_atom_count'], 13)
        self.assertTrue(all(r['chain'] == 'B' for r in unbound['residues']))
        with self.assertRaisesRegex(ValueError, 'must occur'):
            self.inspect(value, chains=['chainID B'])

    def test_missing_explicit_chemistry_or_unsupported_caps_cannot_be_guessed(self):
        for field in DECISIONS:
            missing = decisions(); missing.pop(field)
            with self.subTest(field=field), self.assertRaisesRegex(ValueError, 'explicit chemistry'):
                self.inspect(chemistry=missing)
        unsupported = decisions(); unsupported['protein_termini'] = 'guess-at-pH'
        with self.assertRaisesRegex(ValueError, 'external preparation'):
            self.inspect(chemistry=unsupported)

    def test_histidine_requires_exact_tautomer_for_each_selected_residue(self):
        value = pdb().replace(b'ALA', b'HIS')
        with self.assertRaisesRegex(ValueError, 'HID/HIE/HIP.*A:2'):
            self.inspect(value)
        explicit = decisions(); explicit['histidines'] = {'A:2': 'HIE'}
        observed = self.inspect(value, explicit)
        self.assertEqual(observed['residues'][1]['native_resname'], 'HIE')
        explicit['histidines']['B:2'] = 'HID'
        with self.assertRaisesRegex(ValueError, 'all and only'):
            self.inspect(value, explicit)

    def test_existing_histidine_identity_cannot_be_silently_changed(self):
        explicit = decisions(); explicit['histidines'] = {'A:2': 'HID'}
        with self.assertRaisesRegex(ValueError, 'conflicts with input identity'):
            self.inspect(pdb().replace(b'ALA', b'HIP'), explicit)

    def test_modified_residue_is_not_canonicalized(self):
        for modified in (b'MSE', b'PSU', b'5MC', b'ASH'):
            with self.subTest(modified=modified), self.assertRaisesRegex(ValueError, 'Unsupported/modified'):
                self.inspect(pdb().replace(b'ALA', modified))

    def test_partial_occupancy_altloc_and_multiple_models_are_rejected(self):
        lines = pdb().decode().splitlines()
        for change in ('occupancy', 'altloc', 'models'):
            edited = lines.copy()
            if change == 'occupancy':
                edited[0] = edited[0][:54] + '  0.50' + edited[0][60:]
            elif change == 'altloc':
                edited[0] = edited[0][:16] + 'A' + edited[0][17:]
            else:
                edited = ['MODEL        1', *edited, 'ENDMDL', 'MODEL        2', *edited, 'ENDMDL']
            with self.subTest(change=change), self.assertRaises(ValueError):
                self.inspect(('\n'.join(edited) + '\n').encode())

    def test_chain_breaks_and_missing_linkage_atoms_are_not_repaired(self):
        missing = b'\n'.join(line for line in pdb().splitlines() if not (line[12:16].strip() == b'N' and line[22:26].strip() == b'2'))
        with self.assertRaisesRegex(ValueError, 'Missing polymer linkage'):
            self.inspect(missing)
        distant = pdb().decode().splitlines()
        line = distant[4]
        distant[4] = line[:30] + ' 100.000' + line[38:]
        with self.assertRaisesRegex(ValueError, 'Broken/unphysical'):
            self.inspect(('\n'.join(distant) + '\n').encode())

    def test_explicit_connectivity_is_not_silently_discarded(self):
        with self.assertRaisesRegex(ValueError, 'CONECT'):
            self.inspect(pdb() + b'CONECT    1    5\n')

    def test_repeated_chain_segments_do_not_merge_implicitly(self):
        duplicate = pdb(('A', 'B')).replace(b' B   ', b' A   ')
        with self.assertRaises(ValueError):
            self.inspect(duplicate)

    def test_template_coverage_rejects_missing_sidechain_or_added_modification(self):
        with tempfile.TemporaryDirectory() as folder:
            ff = Path(folder)
            # Atom-coverage parser fixture only; these are not physical FF parameters.
            sections = []
            for name, names, charge in [('NGLY', ['N', 'CA', 'C', 'O'], 1),
                                        ('ALA', ['N', 'CA', 'CB', 'C', 'O'], 0),
                                        ('CGLY', ['N', 'CA', 'C', 'O', 'OXT'], -1)]:
                sections.append('[ ' + name + ' ]\n[ atoms ]\n' + '\n'.join(
                    f'{atom} dummy {charge if i == 0 else 0} {i + 1}' for i, atom in enumerate(names)))
            (ff / 'aminoacids.rtp').write_text('\n'.join(sections))
            normal = validate_templates(self.inspect(), ff)
            self.assertEqual(normal['residues'][-1]['expected_heavy_names'], ['C', 'CA', 'N', 'O', 'OXT'])
            missing = self.inspect(); missing['residues'][1]['atoms'] = [a for a in missing['residues'][1]['atoms'] if a['name'] != 'CB']
            with self.assertRaisesRegex(ValueError, 'Missing heavy atoms'):
                validate_templates(missing, ff)
            modified = self.inspect()
            extra = copy.deepcopy(modified['residues'][1]['atoms'][-1]); extra['normalized_name'] = 'O2'
            modified['residues'][1]['atoms'].append(extra)
            with self.assertRaisesRegex(ValueError, 'modified chemistry is not canonicalized'):
                validate_templates(modified, ff)

    def test_rejected_input_retains_original_bytes_and_never_starts_native_tools(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder); source = root / 'input.pdb'
            value = pdb().replace(b'ALA', b'PSU'); source.write_bytes(value)
            with patch('md.preparation.subprocess.run') as native, self.assertRaises(ValueError):
                prepare(source, root / 'out', runtime_prefix=root / 'unavailable', force_field='example',
                        water_model='tip3p', salt_molar=.15, box_margin_nm=1.2, temperature_kelvin=300,
                        ph=7.4, protonation_review='Explicit chemistry reviewed for this test', chemistry_decisions=decisions())
            native.assert_not_called()
            self.assertEqual((root / 'out/source.pdb').read_bytes(), value)
            receipt = json.loads((root / 'out/receipt.json').read_text())
            self.assertEqual(receipt['state'], 'failed')
            self.assertEqual(receipt['source_sha256'], hashlib.sha256(value).hexdigest())
            self.assertFalse((root / 'out/assets').exists())


@unittest.skipUnless(os.environ.get('BIO_MD_TEST_RUNTIME'), 'Set BIO_MD_TEST_RUNTIME for real native preparation')
class NativePreparationTests(unittest.TestCase):
    def test_native_warning_blocks_publication_even_with_zero_exit_code(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder); source = root / 'input.pdb'; source.write_bytes(pdb())
            native_run = subprocess.run
            def inject_warning(argv, **kwargs):
                result = native_run(argv, **kwargs)
                if argv[1] == 'grompp' and result.returncode == 0:
                    kwargs['stdout'].write(b'\nWARNING 1 [qualification fixture]: explicit warning must reject\n')
                return result
            with patch('md.preparation.subprocess.run', side_effect=inject_warning), self.assertRaisesRegex(ValueError, 'grompp warning'):
                prepare(source, root / 'out', runtime_prefix=os.environ['BIO_MD_TEST_RUNTIME'],
                        force_field='amber99sb-star-ildn-mut', water_model='tip3p', salt_molar=.15,
                        box_margin_nm=1.2, temperature_kelvin=300, ph=7.4,
                        protonation_review='Canonical fixture; injected native warning verifies publication boundary.',
                        chemistry_decisions=decisions())
            self.assertFalse((root / 'out/assets').exists())
            report = json.loads((root / 'out/receipt.json').read_text())
            self.assertEqual(report['state'], 'failed')
            self.assertEqual(report['commands'][-1]['exit_code'], 0)

    def test_real_gromacs_prepares_selected_protein_and_preserves_source(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder); source = root / 'input.pdb'; value = pdb(('A', 'B')); source.write_bytes(value)
            report = prepare(source, root / 'out', runtime_prefix=os.environ['BIO_MD_TEST_RUNTIME'],
                             force_field='amber99sb-star-ildn-mut', water_model='tip3p', salt_molar=.15,
                             box_margin_nm=1.2, temperature_kelvin=300, ph=7.4,
                             protonation_review='Canonical software fixture: charged termini, standard side chains, no disulfides.',
                             chemistry_decisions=decisions(), chains=['B'])
            self.assertEqual(report['state'], 'complete')
            self.assertEqual(report['input_selection']['selected_chains'], ['B'])
            self.assertEqual(sum(len(r['heavy_atom_mapping']) for r in report['residue_audit']), 13)
            self.assertTrue(all(r['prepared_chain'] == 'B' for r in report['residue_audit']))
            self.assertAlmostEqual(report['solvation']['final_charge_e'], 0, places=4)
            self.assertEqual((root / 'out/assets/source.pdb').read_bytes(), value)
            topology = (root / 'out/assets/prepared.top').read_text()
            self.assertNotIn('#include', topology)
            self.assertTrue(all('mdrun' not in command['argv'] for command in report['commands']))
            self.assertFalse(report['molecular_dynamics_executed'])
            self.assertFalse(report['paid_compute_requested'])
            self.assertEqual(len(report['commands']), 6)
            self.assertTrue(all(command['exit_code'] == 0 for command in report['commands']))

    def test_real_installed_templates_reject_missing_heavy_atoms_before_gromacs(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder); source = root / 'input.pdb'
            source.write_bytes(b'\n'.join(line for line in pdb().splitlines() if line[12:16].strip() != b'CB'))
            with patch('md.preparation.subprocess.run') as native, self.assertRaisesRegex(ValueError, 'Missing heavy atoms'):
                prepare(source, root / 'out', runtime_prefix=os.environ['BIO_MD_TEST_RUNTIME'],
                        force_field='amber99sb-star-ildn-mut', water_model='tip3p', salt_molar=.15,
                        box_margin_nm=1.2, temperature_kelvin=300, ph=7.4,
                        protonation_review='Canonical software fixture with a deliberately deleted heavy atom.',
                        chemistry_decisions=decisions())
            native.assert_not_called()


if __name__ == '__main__':
    unittest.main()
